name: Changelog Generator
on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  changelog:
    name: Chanegelog Generator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: etcdigital/pull-request-changelog@master
        with:
          token: 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